### ISSUE TITLE
General Bug Testing

### ISSUE THREAD

**Issue by cmcollander** [cmcollander/CompSciGUI#25] opened 2015-04-04 04:46 UTC
We just need to test out the program enough to find any bugs and post them here for one of us to fix

**Comment by cmcollander** [comment] 2015-04-08 14:29
In part of this, lets try out some complicated map designs. Such as All land with 10 docks placed randomly, to see how the program handles it. We can assume there will be a curveball or two in Becker's map

**Comment by rafeykhan** [comment] 2015-04-13 22:35
general bugs. Please check whether these are actual bugs or if this is how it was intended to be:
wanted to make sure before making changes.

-allows creation of enterprise when no godzilla
-allows creation of multiple enterprises (which throws an exception)
-does not allow drag and drop for enterprise on 2D map
-if enterprise already on 2D map, doesnot build model for it in 3D simulation. (hence Godzilla gets eaten by an invisible enterprise)

**Comment by cmcollander** [comment] 2015-04-14 00:05
Most of these bugs were kind of known and expected upon writing the code. I don't really have time to really incorporate the Enterprise full force like the other objects on the map.
1. No enterprise should be allowed to be created without Godzilla, as Godzilla is the entire reason for the Enterprise to begin with. Enterprise doesn't care about ships, or monsters. Only Godzilla.
2. You'll notice that the new enterprises are not actually really there, just the models. But I can easily limit this to one only so I will do that.
3. Yeah, it would be too much work to incorporate dragging right now. 
3. lol, yeah, i witnessed this earlier today. I'll see what I can do to get this working.

Since the Enterprise is a hidden button anways, only working in 3D mode, the TA 'should' never even end up messing with the enterprise. The only time Enterprise will be shown is at the end of the demonstration, so we can be sure to just make sure none of these errors happen during the demo

**Comment by rafeykhan** [comment] 2015-04-14 00:34
Yeah it would be too much work lol
2nd and 4th are now fixed btw.

**Comment by cmcollander** [comment] 2015-04-14 00:43
I fixed the first one as well, leaving only #3. But surprisingly, I think I can do this easily. Working on it now

**Comment by cmcollander** [comment] 2015-04-14 00:47
Enterprise is now draggable!

**Comment by rafeykhan** [comment] 2015-04-14 00:48
Nice!

**Comment by cmcollander** [comment] 2015-04-14 00:49
Ok! We are on the final stretch! Mess around with everything, figure out any bugs, and I'll work on creating a new full custom training map for us to test out with! Look for any bugs, post them here as Issues ASAP, and we will meet up at the Engineering Library in Nedderman at 12:30 tomorrow!

**Closed as completed** 2015-05-06 05:36 UTC
